config/routes.rb
Rails.application.routes.draw do
  resources :applicants, only: [:create, :update, :edit, :show, :new]
  resources :funnels, only: [:index]
  resource :session, only: [:create, :new]
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  PHONE_TYPES = ['iPhone 6/6 Plus', 'iPhone 6s/6s Plus', 'iPhone 5/5S', 'iPhone 4/4S', 'iPhone 3G/3GS', 'Android 4.0+ (less than 2 years old)', 'Android 2.2/2.3 (over 2 years old)', 'Windows Phone', 'Blackberry', 'Other']
  REGIONS = ['San Francisco Bay Area', 'Chicago', 'Boston', 'NYC', 'Toronto', 'Berlin', 'Delhi']
  WORKFLOW_STATES = ['applied', 'quiz_started', 'quiz_completed', 'onboarding_requested', 'onboarding_completed', 'hired', 'rejected']

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true
  validates :phone_type, presence: true
  validates :workflow_state, presence: true
  validates :region, presence: true
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :require_login, only: [:edit, :update]

  def new
    @applicant = Applicant.new
  end

  def create
    @applicant = Applicant.new(applicant_params)
    @applicant.workflow_state = 'applied'
    if @applicant.save
      flash[:notice] = 'Application submitted! Edit you application below'
      login_applicant @applicant
      redirect_to action: 'edit', id: @applicant
    else
      flash.now[:errors] = @applicant.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def edit
    @applicant = Applicant.find(params[:id])
    redirect_to(new_session_path) unless @applicant == current_applicant
  end

  def update
    @applicant = Applicant.find(params[:id])
    if @applicant.update_attributes(applicant_params)
      flash.now[:notice] = 'Application updated!'
    else
      flash.now[:errors] = @applicant.errors.full_messages.join(', ')
    end
    render 'edit'
  end

  def show
    @applicant = Applicant.find(params[:id])
  end

  private

  def applicant_params
    params.require(:applicant).permit(:first_name, :last_name, :email, :phone,
                                      :phone_type, :workflow_state, :region)
  end

  def require_login
    redirect_to(new_applicant_path) unless logged_in?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_applicant, :login_applicant, :logged_in?

  def current_applicant
    @current_applicant ||= Applicant.find_by(email: session[:email])
  end

  def logged_in?
    !current_applicant.nil?
  end

  def login_applicant(applicant)
    session[:email] = applicant.email
  end
end

app/controllers/funnels_controller.rb
class FunnelsController < ApplicationController
  def index
    weeks = weeks_from_range('2014-12-02', '2014-12-27')
    @funnel = {}
    weeks.each do |week|
      applicants = Applicant.where(created_at:
        week[:start_date]..week[:end_date]).group(:workflow_state).count
      @funnel[range_to_string(week)] = applicants
    end
    respond_to do |format|
      format.html { @chart_funnel = formatted_funnel }
      format.json { render json: @funnel }
    end
  end

  private

  def weeks_from_range(start_date, end_date)
    date_ranges = []
    parsed_start_date = Date.parse(start_date)
    parsed_end_date = Date.parse(end_date)

    current_monday = parsed_start_date.beginning_of_week
    while current_monday < parsed_end_date
      date_ranges << { start_date: current_monday,
                       end_date: current_monday + 6 }
      current_monday += 7
    end
    date_ranges
  end

  def range_to_string(date_range)
    date_range[:start_date].strftime('%Y-%m-%d') + '-' + \
      date_range[:end_date].strftime('%Y-%m-%d')
  end

  # generates a formatted version of the funnel for display in d3
  def formatted_funnel
    formatted = Hash.new { |h, k| h[k] = [] }

    @funnel.each do |date, state_counts|
      state_counts.each do |state, count|
        formatted[state] << { label: date, value: count }
      end
    end

    formatted.map do |k, v|
      {
        key: k.humanize,
        values: v
      }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    applicant = Applicant.find_by(email: params[:email])
    if applicant
      login_applicant applicant
      flash[:notice] = "Hello, #{applicant.first_name}!"
      redirect_to edit_applicant_path(applicant)
    else
      flash.now[:error] = 'Email not found'
      render 'new'
    end
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/applicants/_form.html.haml
.form-group
  =f.label :first_name
  =f.text_field(:first_name, class: 'form-control', placeholder: 'First name')
.form-group
  =f.label :last_name
  =f.text_field(:last_name, class: 'form-control', placeholder: 'Last name')
.form-group
  =f.label :email
  =f.text_field(:email, class: 'form-control', placeholder: 'example@test.com')
.form-group
  =f.label :phone
  =f.text_field(:phone, class: 'form-control', placeholder: '555 555 5555')
.form-group
  %label{:for => "phoneType"} Select phone:
  %select#phoneType.form-control{:name => "applicant[phone_type]"}
    - Applicant::PHONE_TYPES.each do |phone|
      %option #{phone}
.form-group
  %label{:for => "region"} Select region:
  %select#region.form-control{:name => "applicant[region]"}
    - Applicant::REGIONS.each do |region|
      %option #{region}

app/views/applicants/edit.html.haml
.content
  =form_for @applicant do |f|
    =render 'form', :f => f
    %button.btn.btn-default{:id => "form-submit", :type => "submit"} Submit

app/views/applicants/new.html.haml
.content
  =form_for @applicant do |f|
    .page-one
      =render 'form', :f => f
      %button.btn.btn-default{:id => "form-next", :type => "button"} Next
    .page-two
      Please confirm that you consent to a background check:
      .checkbox
        %label
          %input{:type => "checkbox", :id => "background-check", :value => ""}>/
          Confirm background check

      %button.btn.btn-default{:id => "form-submit", :type => "submit"} Submit

:javascript
  $('#form-submit').prop('disabled', true);
  $('#form-next').click(function () {
    $('.page-one').hide()
    $('.page-two').show()
  })
  $('#background-check').click(function () {
    if (this.checked) {
      $('#form-submit').prop('disabled', false);
    } else {
      $('#form-submit').prop('disabled', true);
    }
  })

app/views/applicants/show.html.haml
= @applicant.first_name
= @applicant.last_name
= @applicant.email
= @applicant.phone
= @applicant.phone_type
= @applicant.workflow_state
= @applicant.region

app/views/funnels/index.html.haml
- # feel free to override any and all parts of this to make it more to your liking
- # this is a very bare-bones implementation of a funnel analytics view

.container
  .row
    #funnel-chart
      %svg

  .row
    %table.table
      %thead
        %tr
          %th

          - Applicant::WORKFLOW_STATES.each do |state|
            %th= state.humanize
      %tbody
        - @funnel.each do |date, state_counts|
          %tr
            %td= date
            - Applicant::WORKFLOW_STATES.each do |state|
              %td= state_counts[state]

:coffeescript
  data = #{@chart_funnel.to_json};

  nv.addGraph ->
    chart = nv.models.multiBarChart()
      .x((d) -> d.label)
      .y((d) -> d.value)
      .margin(top: 50, right: 20, bottom: 50, left: 100)
      .tooltips(true)
      .transitionDuration(350)

    chart.yAxis.tickFormat(d3.format(',.2f'))
    d3.select('#funnel-chart svg').datum(data).call(chart)
    nv.utils.windowResize(chart.update)

    chart

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Shopper Application', new_applicant_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li
  = link_to 'Funnel Analytics', funnels_path
%li
  - if logged_in?
    = link_to 'Edit your application', edit_applicant_path(current_applicant)
  - else
    = link_to 'Login to edit your application', new_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? yield(:title) : 'Shopper Challenge'

    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %meta{:name => 'description', content: 'Shopper Challenge'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags

  %body
    %header
      = render 'layouts/navigation'

    %main{role: 'main'}
      = render 'layouts/messages'
      = yield